services:
  app: 
    container_name: "vendor-machine-api"
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - vending-machine-network
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URI: ${DATABASE_URI:-postgres://postgres:password@db:5432/postgres}
    depends_on:
      - db
  db:
    image: postgres
    container_name: "vending-machine-db"
    restart: on-failure
    networks:
      - vending-machine-network
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
networks:
  vending-machine-network:
    driver: bridge
volumes:
  app-data:
  db-data:
  app-node-modules: